import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans } from "next/font/google";
import { cn } from "../lib/utils";
import ContextProvider from "@/contexts/ContextProvider";

export const fontSans = FontSans({
   subsets: ["latin"],
   variable: "--font-sans",
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body
            className={cn(
               `${fontSans.className}`,
               "flex items-center justify-center",
               "h-screen w-screen"
            )}
         >
            <ContextProvider>{children}</ContextProvider>
         </body>
      </html>
   );
}
